// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzI4ZxMQYMFOLDyqzhtPaWSBKTXNctLXY',
    appId: '1:58643702323:web:1aec3f440a536b4d537946',
    messagingSenderId: '58643702323',
    projectId: 'lavieapp-9b0d',
    authDomain: 'lavieapp-9b0d.firebaseapp.com',
    storageBucket: 'lavieapp-9b0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBysM10dBjHxVwJ2ktXpbrI6g4dXsq1xxw',
    appId: '1:58643702323:android:5fc285b4abc7d792537946',
    messagingSenderId: '58643702323',
    projectId: 'lavieapp-9b0d',
    storageBucket: 'lavieapp-9b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChhK7Ta5gRUH4g2UVriKioaIdy85hBpAU',
    appId: '1:58643702323:ios:6717bccf57334dce537946',
    messagingSenderId: '58643702323',
    projectId: 'lavieapp-9b0d',
    storageBucket: 'lavieapp-9b0d.firebasestorage.app',
    iosBundleId: 'com.example.projetoios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChhK7Ta5gRUH4g2UVriKioaIdy85hBpAU',
    appId: '1:58643702323:ios:6717bccf57334dce537946',
    messagingSenderId: '58643702323',
    projectId: 'lavieapp-9b0d',
    storageBucket: 'lavieapp-9b0d.firebasestorage.app',
    iosBundleId: 'com.example.projetoios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzI4ZxMQYMFOLDyqzhtPaWSBKTXNctLXY',
    appId: '1:58643702323:web:33c7e40c54c04c34537946',
    messagingSenderId: '58643702323',
    projectId: 'lavieapp-9b0d',
    authDomain: 'lavieapp-9b0d.firebaseapp.com',
    storageBucket: 'lavieapp-9b0d.firebasestorage.app',
  );

}